---
name: SDK

"on":
  workflow_dispatch:
  push:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  test-server:
    name: Build test server
    runs-on: ubuntu-latest

    steps:
      - name: Set up Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print version of protoc
        run: protoc --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.2.0

      - name: Compile test-server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p test-server

      - name: Upload test-server
        uses: actions/upload-artifact@v3
        with:
          name: test-server
          path: target/debug/test-server

  python-sdk:
    name: Test Python SDK
    runs-on: ubuntu-latest
    needs:
      - test-server
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Install Python SDK
        run: python -m pip install sdk/python/.
      - name: Download test-server
        uses: actions/download-artifact@v3
        with:
          name: test-server
          path: bin
      - name: Set permissions for test-server
        run: chmod +x ./bin/test-server
      - name: Start test-server
        run: ./bin/test-server &
      - name: Run Python SDK test
        run: python sdk/python/test.py
