---
name: SDK

"on":
  workflow_dispatch:
  push:

env:
  CARGO_INCREMENTAL: 0
  CARGO_PROFILE_TEST_DEBUG: 0

jobs:
  test-server:
    name: Build test server
    runs-on: ubuntu-latest

    steps:
      - name: Set up Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Print version of protoc
        run: protoc --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Cache build artifacts
        uses: swatinem/rust-cache@v2.2.0

      - name: Compile test-server
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: -p test-server

      - name: Upload test-server
        uses: actions/upload-artifact@v3
        with:
          name: test-server
          path: target/debug/test-server

  python-sdk:
    name: Test Python SDK
    runs-on: ubuntu-latest
    needs:
      - test-server
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip and echo versions
        run: |
          python -m pip install --upgrade pip
          python --version
          python -m pip --version
      - name: Install Python SDK
        run: tree sdk/python && python -m pip install sdk/python/.
      - name: Verify Python SDK
        run: |
          tree "$(python -c 'print(__import__("pathlib").Path(__import__("atc").__file__).parent.resolve())')"
      - name: Archive atc package
        uses: actions/upload-artifact@v3
        if: ${{ matrix.python-version }} == '3.8'
        with:
          name: atc-package-38
          path: /opt/hostedtoolcache/Python/3.8.14/x64/lib/python3.8/site-packages/atc
      - name: Download test-server
        uses: actions/download-artifact@v3
        with:
          name: test-server
          path: bin
      - name: Run Python example
        run: |
          chmod +x ./bin/test-server
          ./bin/test-server &
          sleep 3
          python examples/python/play.py
